# Generated by Django 5.1.1 on 2025-01-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALORA', '0002_decoration_decoration_name_food_food_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
