# Generated by Django 5.1.1 on 2025-01-30 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALORA', '0004_bookings_food_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='event_id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='decoration_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='event_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='bookings',
            name='no_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='decoration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ALORA.decoration'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ALORA.food'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='photography_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
